### ISSUE TITLE
Rectangles?

### ISSUE THREAD

**Issue by emeeks** [wereHamster/simple-square-packing#1]
Would it be feasible to make this work with any rectangular shape and not just squares?

**Comment by wereHamster** [comment]
I fear that it would significantly increase the complexity of the algorithm if I wanted to keep all the edge cases covered. Have you considered using d3 force layout instead?

**Comment by emeeks** [comment]
Yes I wrote a bounding box collision detection and found the results to be rather poor visually, whereas this simple packing, but done with rectangles, would work much better. I'm not much for actual algorithm design but I'll see if I can dive into it. Even something that didn't handle edge cases and was clear about the expected size/shape of rectangles would be extremely useful, if only to initially seed a later physical simulation.

**Comment by wereHamster** [comment]
You could still use this algorithm to generate the initial positions and then apply force layout on it. It should work fairly well as long as your rectangles don't have an extremely large aspect ratio (ie. are roughly square-ish).

This kind of algorithm is [NP-hard](https://en.wikipedia.org/wiki/NP-hardness). I simplified it by assuming squares and have the largest one in the center and smaller ones towards the outside. If you don't have the same constraint you could try other algorithms which are described in literature.

See also https://en.wikipedia.org/wiki/Packing_problems, https://www.codeproject.com/Articles/210979/Fast-optimizing-rectangle-packing-algorithm-for-bu 

In particular, if you don't have the need to place the largest rectangles in the center, you can try variations of "sprite packing" algorithms (also called "texture packing", "texture atlas", "sprite sheet"). Here's one such algorithm in JavaScript: https://github.com/jakesgordon/bin-packing
